### ISSUE TITLE
Multi training

### ISSUE THREAD

**Issue by Newera2022** [fairy-stockfish/variant-nnue-pytorch#15]
Thanks

**Comment by ianfab** [comment]
I unfortunately do not have a multi-GPU setup where I could test this, so it is hard for me to tell. What happens when you pass something like `--gpus 2`? Does it fail or just not use more than one GPU?

**Comment by byezilin** [comment]
My server has 8 nvdia graphics cards. The error report was not saved that day. I will try to repeat the operation later to get the error information and feed it back here.

**Comment by byezilin** [comment]
OK, I will first try the previous setting method to get the error report, and then try the method you provided.

**Comment by byezilin** [comment]
Tried several schemes and failed

"0,1" or "0,1," or "0,1," cannot start training successfully

**Comment by byezilin** [comment]
Two graphics cards on the machine

Only [--gpus 0,] and [--gpus "0,"] can start training,

Or [--gpus 1,] and [--gpus "1,"] can also train weights

But it just can't be merged. It's very strange to let two graphics cards work at the same time. I don't know how to set it correctly.

**Comment by ianfab** [comment]
It looks like multiple GPU training isn't supported by the current code. I don't have any multi GPU machines, and normally anyway the training data generation is the bottleneck, so I never looked into that so far.
