### ISSUE TITLE
Questions about xiangqi

### ISSUE THREAD

**Issue by Newera2022** [fairy-stockfish/variant-nnue-pytorch#24]
Excuse me, I want to train through this tool to train greater than the current Xiangqi, which place should I need to modify it? The network trained is only 11MB.

**Comment by ianfab** [comment]
Bigger is not necessarily better.

**Comment by Newera2022** [comment]
Want to make more attempts, but I don't know where to modify the parameters?

**Comment by calcitem** [comment]
http://pikafish.org/
