### ISSUE TITLE
Serializing is throwing an exception

### ISSUE THREAD

**Issue by y0sif** [fairy-stockfish/variant-nnue-pytorch#34]
Im trying to convert a model from .nnue format to .pt format but I'm getting this error:

```
variant-nnue-pytorch/serialize.py", line 203, in read_int32
    raise Exception("Expected: %x, got %x" % (expected, v))
Exception: Expected: 3c103e72, got 1c102b72
```

is there something that I'm missing?

**Comment by ianfab** [comment]
One possible reason for failure when serializing can be that the current variant.py does not fit to the trained NNUE. More I can't say based on the available information, with the exact serialization command as well as the variant.py and the source of the NNUE I might be able to add more.

**Comment by y0sif** [comment]
this one to be exact:

![image](https://github.com/user-attachments/assets/20a65fbf-05d8-43b9-9dfd-4afc4ad8df86)

**Comment by y0sif** [comment]
but now when i try to visualize it I get this error:

```
nnue-pytorch/visualize.py", line 264, in plot_input_weights
    np.arange(int(np.min(img)*127)-1, int(np.max(img)*127)+3)-0.5)/127)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Maximum allowed size exceeded
```

**Comment by ianfab** [comment]
It seems like you are mixing the two repos nnue-pytorch and variant-nnue-pytorch. My fork is for Fairy-Stockfish and chess variants, and it is not compatible with recent Stockfish NNUE architectures that are trained with the nnue-pytorch repo as I still uses a generalized version of HalfKAv2. So depending on the engine you are training for please use the respective repository.

**Comment by y0sif** [comment]
thanks for the clarification, so is there a way to know what the architecture of the nnue in stockfish testing frame work, because all of them share the same extension, and to give you more context I am trying to implement nnue in rust using rust burn, but I am having some issues with it and I'm trying to make sure that my way of constructing the architecture is valid.

**Comment by ianfab** [comment]
As far as I understand your question is only referring to standard chess and official SF, so it is better to ask in their forums.
