### ISSUE TITLE
Extended training data format

### ISSUE THREAD

**Issue by ianfab** [fairy-stockfish/variant-nnue-pytorch#4]
https://github.com/ianfab/variant-nnue-pytorch/tree/largedata
https://github.com/ianfab/variant-nnue-tools/tree/tools_largedata

- [x] extend to 1024 bit
- [x] extend to 7 bit per pocket

**Comment by shuangqiao999** [comment]
Hello  Is largeData suitable for xiangqi training?

**Comment by shuangqiao999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shuangqiao999** [comment]
Thankyou

**Comment by shuangqiao999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by calcitem** [comment]
你好！最好取消一下自动回复。

发件人: shuangqiao999 ***@***.***>
发送时间: Thursday, January 26, 2023 20:26
收件人: fairy-stockfish/variant-nnue-pytorch ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [fairy-stockfish/variant-nnue-pytorch] Extended training data format (Issue #4)

这是来自QQ邮箱的假期自动回复邮件。

您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
